name: Documentation
description: Documentation Request
title: "[Doc]: "
labels: ["documentation"]
body:
  - type: dropdown
    id: section
    attributes:
      label: Section to modify
      description: Which documents should be changed
      multiple: false
      options:
        - "Getting Started"
        - "Install"
        - "First start"
        - "Configure"
        - "Update"
        - "Proxy"
        - "Database"
        - "Media"
        - "Apps"
        - "Advanced"
        - "Developer"
        - ":bulb:New Section"
    validations:
      required: true

  - type: textarea
    id: request
    attributes:
      label: request
      description: Tell us how to improve it
    validations:
      required: true
