name: Repository Maintenance
description: Respository maintenance request
title: "[Chore]: "
labels: ["chore"]
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What should be improved?
      multiple: false
      options:
        - "CI"
        - "Issue template"
        - "PR template"
        - "Other"
    validations:
      required: true
  
  - type: textarea
    id: request
    attributes:
      label: request
      description: Tell us how to improve it.

