name: 'Build docker image on PR'

on:
  pull_request:
  pull_request_target:
    types: [labeled]


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      github.event.pull_request.head.repo.fork == false || 
      (github.event.pull_request.head_repo.fork == true && contains(github.event.pull_request.labels.*.name, 'safe to test'))
    steps:
      - name: test
        run: echo "success"